### ISSUE TITLE
May also work on centos 8 stream

### ISSUE THREAD

**Issue by zhirshya** [TedLeRoy/first-ten-seconds-centos-ubuntu#1]
Hi, I'm a new centos learner and just tried your script on freshly installed centos 8 stream. It seems also work.
I only added:
`|| [ "$osName" == "CentOS Stream" ]`

Script finished with code 0, but with error

> It looks like SSH is not configured to allow key based authentication.
>     Please enable it and re-run this script.

So, I set following keys in /etc/ssh/sshd_config:
```
PasswordAuthentication no
ChallengeResponseAuthentication no
UsePAM no
PermitRootLogin no
StrictModes yes
PubkeyAuthentication yes
```

then did,
`sudo systemctl restart sshd`
made sure ssh daemon was refreshed with new settings, tried again, still having the same error
> It looks like SSH is not configured to allow key based authentication.
>     Please enable it and re-run this script.

Though I restarted sshd in another terminal tab, it shouldn't miss new sshd settings, right?

Thank you for your script.

**Comment by TedLeRoy** [comment]
Hi zhirshya,

Thanks so much for filing a bug. So sorry it took me so long to answer. I thought I'd get notified when a bug was filed.

I'm not sure what the issue is and hadn't planned to support CentOS stream, opting to support Rocky Linux instead going forward. Where did you put `|| [ "$osName" == "CentOS Stream" ]` in your code? Is it in the CentOS section? If so, I would think it would work.

Kind regards,

Ted
